sudo: false
language: rust
rust:
  - beta
  - stable
# https://github.com/huonw/travis-cargo
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
before_install:
  - wget https://github.com/antirez/disque/archive/master.tar.gz -O disque-master.tar.gz
  - tar xf disque-master.tar.gz && cd disque-master/src/ && make && PREFIX=../ make install && cd -
before_script:
  - ./disque-master/bin/disque-server --daemonize yes
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - travis-cargo build && travis-cargo test
after_success:
  - travis-cargo --only stable coveralls --no-sudo --verify
env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
